-- font_families 배치 11

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b29269b7-4ea0-4a56-9d37-5e4276df744c', 'HS산토끼체2.0', 'HsSantoki20', 'HsSantoki20', 'decorative', 'HS산토끼체2.0폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1381', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '95967f53-55d4-4445-ae00-9ab943ed6225', '온글잎 재건사', 'OngleipReconstruction', 'OngleipReconstruction', 'decorative', '온글잎 재건사폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1385', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0a115872-37e1-45f0-9959-d1188ce5f997', '온글잎 주리손편지', 'OnglipJuRiSonPenji', 'OnglipJuRiSonPenji', 'decorative', '온글잎 주리손편지폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1386', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '40bef528-160c-44a3-8844-33afa3e9a914', '온글잎 누카', 'OngleipNuka', 'OngleipNuka', 'decorative', '온글잎 누카폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1387', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f57d99be-3136-43fc-b499-6b919747d05b', '온글잎 류류체', 'OngleipRyuryu', 'OngleipRyuryu', 'decorative', '온글잎 류류체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1388', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '7bce067f-454b-4d01-b5f0-e588a69d98bb', '온글잎 류뚱체', 'OngleipRyudung', 'OngleipRyudung', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1389', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a62be2c6-422d-493f-a9da-86261d6d6ef7', '어비 챠밍체', 'AviCharming', 'AviCharming', 'decorative', '어비 챠밍체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/139', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'ce23eb59-e0a7-46ac-9e01-49dd3f2b05d4', '온글잎 은별', 'OngleipEunbyeol', 'OngleipEunbyeol', 'decorative', '온글잎 은별폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1390', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1995282f-cb8a-4f91-9178-605a5c55a1c1', 'MOVE Sans', 'MoveSans', 'MoveSans', 'gothic', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1391', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c5a53c19-a646-459b-bdcd-45cf8ed7917d', 'Cafe24 Behappy', 'Cafe24Behappy', 'Cafe24Behappy', 'decorative', 'Cafe24 Behappy폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1394', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'af165d7e-3a9d-4b27-bad0-06b04ff204a8', 'Cafe24 Decobox', 'Cafe24Decobox', 'Cafe24Decobox', 'decorative', 'Cafe24 Decobox폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1395', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '37489ace-5ae2-44cd-a1e0-ccde6cae0e3f', 'Cafe24 Decoline', 'Cafe24Decoline', 'Cafe24Decoline', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1396', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd78dff2d-a60f-445a-98c1-8e587f73da4f', 'Cafe24 Decomilk', 'Cafe24Decomilk', 'Cafe24Decomilk', 'decorative', 'Cafe24 Decomilk폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1397', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b6d843f9-aaed-4956-b1ca-a6e314a7452f', 'Cafe24 Decoschool', 'Cafe24Decoschool', 'Cafe24Decoschool', 'decorative', 'Cafe24 Decoschool폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1398', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '87024530-be71-40ec-8dc8-7ac8a0a383e8', 'Cafe24 Decoshadow', 'Cafe24Decoshadow', 'Cafe24Decoshadow', 'decorative', 'Cafe24 Decoshadow폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1399', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c62e018f-341b-4338-816b-15d647b0bc7d', '경기천년제목', 'GyeonggiMillenniumTitle', 'GyeonggiMillenniumTitle', 'decorative', '제스트광고디자인', '사용 가능', 'https://noonnu.cc/font_page/14', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '4e019aac-9a74-4bc4-b119-0f777eac56ad', 'Cafe24 Decozoo', 'Cafe24Decozoo', 'Cafe24Decozoo', 'decorative', 'Cafe24 Decozoo폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1400', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '52ddd259-6d48-40f1-88f5-f7563a6b726c', 'Cafe24 Loving u', 'Cafe24LovingU', 'Cafe24LovingU', 'decorative', 'Cafe24 Loving u폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1401', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b5b97692-8209-4c0e-b4be-c83a906b5058', 'Cafe24 Meongi Black', 'Cafe24MeongiBlack', 'Cafe24MeongiBlack', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1402', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a1eab128-d589-4422-84c8-45edc53982b0', 'Cafe24 Meongi White', 'Cafe24MeongiWhite', 'Cafe24MeongiWhite', 'decorative', 'Cafe24 Meongi White폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1403', NULL, 0, true, false, NOW(), NOW() );
