-- font_families 배치 6

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '16bd6bc6-34fa-4793-8e74-1419f797b032', '학교안심 돌담', 'SchoolSafeStoneWall', 'SchoolSafeStoneWall', 'decorative', '학교안심 돌담폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1209', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '06662665-2feb-4216-aad7-33070286061e', '학교안심 가을소풍', 'SchoolSafeAutumnTrip', 'SchoolSafeAutumnTrip', 'decorative', '학교안심 가을소풍폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1212', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6ada27ac-379d-4abf-8809-b3aa434a2cf2', '학교안심 꾸러기', 'SchoolSafetyKid', 'SchoolSafetyKid', 'decorative', '학교안심 꾸러기폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1214', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6e02efd8-6b7f-4176-9bcc-05d3a1145fed', '학교안심 곧은제목', 'SchoolSafetyStraightTitle', 'SchoolSafetyStraightTitle', 'decorative', '학교안심 곧은제목폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1215', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0fda84f0-33cb-48e1-8439-24e27ec39ccb', '학교안심 맑은날', 'SchoolSafetySunnyDay', 'SchoolSafetySunnyDay', 'decorative', '학교안심 맑은날폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1217', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a23beb92-c6fb-4033-b39e-6b96acaa6ac0', '학교안심 산뜻바탕', 'SchoolSafetySans', 'SchoolSafetySans', 'serif', '학교안심 산뜻바탕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1219', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c749d3d3-7f1e-43ff-bfd2-63f501bc79d0', '둘기마요', 'DulgiMayo', 'DulgiMayo', 'decorative', '둘기마요폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/122', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6e55fc4b-dad4-4efe-81fb-b3c5b86e1ab1', '학교안심 산뜻돋움', 'SchoolSafeSansDoodum', 'SchoolSafeSansDoodum', 'decorative', '학교안심 산뜻돋움폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1221', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c48e01ed-1b62-43ef-b166-37d8cc49fea3', '학교안심 우주', 'SchoolSafeUniverse', 'SchoolSafeUniverse', 'decorative', '학교안심 우주폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1223', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd0c3ffd8-0f5d-4475-9c1f-152ab2ba121a', 'I AM A PLAYER', 'IAmAPlayer', 'IAmAPlayer', 'decorative', 'I AM A PLAYER폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1224', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e2402340-0b95-4924-8f92-ae2a33c5bf11', '인천교육힘찬체', 'IncheonEducationHimchan', 'IncheonEducationHimchan', 'decorative', '인천교육힘찬체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1225', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'fe212270-4043-414f-89ee-15c0ebf273ef', '인천교육자람체', 'IncheonEducation', 'IncheonEducation', 'decorative', '인천교육자람체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1226', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '753a693a-9474-41bd-9065-47ab96873f18', '인천교육시민체', 'IncheonEducationCitizen', 'IncheonEducationCitizen', 'decorative', '인천교육시민체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1227', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b1488107-07ee-4e96-a352-78665c414c5a', '인천교육소통체', 'IncheonEducationCommunication', 'IncheonEducationCommunication', 'decorative', '인천교육소통체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1228', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '3ebc3c1f-c234-4df9-9084-6a24db4617bf', '엘리스 DX널리체', '엘리스 DX널리체', 'Elice DX Neolli'');

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e90f10a7-c0e4-4faa-a056-8c5c2605e4a3', '함초롬체', 'Hamchorom', 'Hamchorom', 'decorative', '함초롬체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/123', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c40c741a-818e-45c8-a3c1-78dae2df76bf', '전주공예명조체', 'JeonjuCraftMyungjo', 'JeonjuCraftMyungjo', 'serif', '전주공예명조체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1234', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '428eedc8-5d37-4cf5-bc06-7517cafa8e1c', '전주공예고딕체', 'JeonjuCraftGothic', 'JeonjuCraftGothic', 'gothic', '전주공예고딕체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1235', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '7a8af264-5e76-4752-9873-abd4c6d13e0e', '세종학당', '세종학당', 'UnknownFont', 'decorative', '세종학당폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1237', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '472a5707-51b1-4aa8-af77-1210b7b06b3b', '국민연금체', 'NationalPension', 'NationalPension', 'decorative', '국민연금체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1239', NULL, 0, true, false, NOW(), NOW() );
