-- font_families 배치 13

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'fd76c988-f866-4f47-8548-ec52310fc4a7', '어비 은디체', 'EobiEundi', 'EobiEundi', 'decorative', '어비 은디체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/145', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '21dfd30b-fb21-427b-ab0e-e8d6d87dc553', '전남교육바른체', 'JeonnamEducationBarun', 'JeonnamEducationBarun', 'decorative', '전남교육바른체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1451', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f4e4974b-45a4-43c0-b7aa-fe539bdc7edb', '전남교육또박체', 'JeonnamEducationTtobaks', 'JeonnamEducationTtobaks', 'decorative', '전남교육또박체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1453', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '044c555e-5181-4e0a-b4e2-adcf0e3639ba', '전남교육유나체', 'JeonnamEducationYuna', 'JeonnamEducationYuna', 'decorative', '전남교육유나체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1454', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6a04a958-7793-467b-b703-b2ef806422a4', '페이퍼로지', 'Paperozi', 'Paperozi', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1456', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '9e676583-4ee6-4f68-8054-389c1ba419cf', '어비 은경체', 'EobiEunGyeong', 'EobiEunGyeong', 'decorative', '어비 은경체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/146', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'cde3527c-8c4b-40f0-b7c6-1581d106fbe1', '온글잎 때롬체', 'OngleipTterom', 'OngleipTterom', 'decorative', '온글잎 때롬체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1465', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5c8be60a-c528-4b71-a9e5-e2aad35e3b97', '수박양체', 'WatermelonYang', 'WatermelonYang', 'decorative', '수박양체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1466', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b7817488-d46b-4f22-9385-de484434e013', '삼립크리미 화이트체', 'SamlipCreamyWhite', 'SamlipCreamyWhite', 'decorative', '삼립크리미 화이트체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1467', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f6fd4fab-aa54-4476-b822-28a3cb4e65c9', '학교안심 알림장', 'SchoolSafetyNotification', 'SchoolSafetyNotification', 'decorative', '학교안심 알림장폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1468', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c44f50cb-e832-4806-8229-84b55667769a', '어비 뒤죽박죽체', 'EobiJumbled', 'EobiJumbled', 'decorative', '어비 뒤죽박죽체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/147', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '31ec60d5-38be-4981-bd61-116e5d8747d5', '학교안심 받아쓰기', 'SchoolSafeDictation', 'SchoolSafeDictation', 'decorative', '학교안심 받아쓰기폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1470', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '37cd7ae2-44a5-4aea-948d-4b62adcff4cf', '학교안심 별빛하늘', 'SchoolSafetyStarrySky', 'SchoolSafetyStarrySky', 'decorative', '학교안심 별빛하늘폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1471', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '239583ed-b72e-4ae3-ac63-a397b270b76d', '학교안심 별자리', 'SchoolSafetyConstellation', 'SchoolSafetyConstellation', 'decorative', '학교안심 별자리폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1473', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a5975477-3c01-4ad4-84a6-333c9f13a11d', '학교안심 칠판지우개', 'SchoolSafetyChalkboardEraser', 'SchoolSafetyChalkboardEraser', 'decorative', '학교안심 칠판지우개폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1475', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e2a2f25d-063f-48ed-b8f6-aa851603ffe5', '학교안심 출석부', 'SchoolSafetyAttendanceBook', 'SchoolSafetyAttendanceBook', 'decorative', '학교안심 출석부폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1477', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd2c0a06c-e7e4-4fea-b76a-d066fa4a1390', '학교안심 둥근미소', 'SchoolSafetyRoundedSmile', 'SchoolSafetyRoundedSmile', 'decorative', '학교안심 둥근미소폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1479', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd52cf140-b13e-45b1-a4f8-eb1ef6b88006', '어비 지민2체', 'AviJimin2', 'AviJimin2', 'decorative', '어비 지민2체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/148', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'dbb6bc47-0609-400b-ac89-98d749188e42', '학교안심 그림일기', 'SchoolSafetyPictureDiary', 'SchoolSafetyPictureDiary', 'decorative', '학교안심 그림일기폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1481', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd84442df-6e6f-48b1-9232-ed38fdf6e05b', '학교안심 나들이', 'SchoolSafeOuting', 'SchoolSafeOuting', 'decorative', '학교안심 나들이폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1482', NULL, 0, true, false, NOW(), NOW() );
