-- font_families 배치 1

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2373259b-5218-43c4-9c0c-cc37d635d755', '한수원 한울림체', 'HansuwonHanullim', 'HansuwonHanullim', 'decorative', '한수원 한울림체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/10', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '771baf05-0f71-44d4-ac8c-d9e8070e8d91', '모노플렉스WideNerd', 'MonoplexWideNerd', 'MonoplexWideNerd', 'decorative', '모노플렉스WideNerd폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1013', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1d13e606-a95a-4ac6-b317-5f876e62d49d', '모노플렉스WideNerd Italic', 'MonoplexWidenerdItalic', 'MonoplexWidenerdItalic', 'decorative', '모노플렉스WideNerd Italic폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1014', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '837dd688-2de5-4236-9bea-66b8ca4010f3', '카페24 클래식타입', 'Cafe24ClassicType', 'Cafe24ClassicType', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1035', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f623ae4d-a384-4617-bdd9-0e1c74879944', '꽃소금체', 'Kkotsogum', 'Kkotsogum', 'decorative', '꽃소금체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1036', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '87103a11-f9fb-4a42-b425-28733d594c48', 'HS굴토끼체', 'HsGultokki', 'HsGultokki', 'decorative', 'HS굴토끼체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1038', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8b060bd1-d498-45fd-9219-c919ce06beb5', 'KOFIH이종욱체', 'KofihJongwook', 'KofihJongwook', 'decorative', 'KOFIH이종욱체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1040', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '064bf068-ec0e-455b-bbec-2343611c3d86', '태나다체', 'Taenada', 'Taenada', 'decorative', '태나다체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1042', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a1bfb3b3-bcd0-4a4f-bdcb-5f7a54f0b9cc', '안성탕면체', 'Ansungtangmyeon', 'Ansungtangmyeon', 'decorative', '안성탕면체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1044', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'ed5e0543-63d5-499c-a19d-05ba762831cc', '안성탕면 ESG에코체', 'AnsungtangmyunEsgEco', 'AnsungtangmyunEsgEco', 'decorative', '안성탕면 ESG에코체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1046', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd95c3886-36ac-4960-a7ce-2e3bf77c596e', '좋은이웃체', 'GoodNeighbor', 'GoodNeighbor', 'decorative', '좋은이웃체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1047', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5448452e-e74e-42fd-94b0-e4bf77b6c01b', '귀염발랄체', 'Gyeombalbal', 'Gyeombalbal', 'decorative', '귀염발랄체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1049', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f192c913-ee9d-4887-a27d-c2572aae20b0', 'LINE Seed', 'LineSeed', 'LineSeed', 'decorative', 'LINE Seed폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1050', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '09f92959-98f2-4ac0-a6a4-624eef4c05a3', '나눔스퀘어 네오', 'NanumSquareNeo', 'NanumSquareNeo', 'decorative', '나눔스퀘어 네오폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1053', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '93852887-a06f-488f-aaf9-a0273fac8d4f', '선문대체', 'SunmoonUniversity', 'SunmoonUniversity', 'decorative', '선문대체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1054', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c18e463c-26db-4ee4-b309-4f45a46158f2', 'Y콤퓨타체', 'YKompyuta', 'YKompyuta', 'decorative', 'Y콤퓨타체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1056', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '958d8e7c-45ae-4a0e-b43f-2392896a6533', '푸라닭 젠틀 고딕', 'PuradakGentleGothic', 'PuradakGentleGothic', 'gothic', '푸라닭 젠틀 고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1057', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e416eeca-fdb7-4766-b303-648d262a8db5', '기후위기-한글', 'ClimateCrisisKorean', 'ClimateCrisisKorean', 'decorative', '기후위기-한글폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1058', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a161b77b-1602-4516-aac4-fb6685dbe3f6', '검은고딕', 'BlackHanSans', 'Black Han Sans', 'gothic', '검은고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://fonts.google.com/specimen/Black+Han+Sans', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '55612bec-d618-448c-92ca-2b7a9a56dc4a', '기후위기-한글 VF', 'ClimateCrisisHangulVf', 'ClimateCrisisHangulVf', 'decorative', '기후위기-한글 VF폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1066', NULL, 0, true, false, NOW(), NOW() );
