-- font_families 배치 8

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '35bfbbfc-f839-4ba6-aae2-d01b1e596892', '서강체', 'Seongang', 'Seongang', 'decorative', '서강체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1291', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f288d231-7c01-40cb-9292-27f75ca78c77', '넥슨 워헤이븐', 'NexonWarhaven', 'NexonWarhaven', 'decorative', '넥슨 워헤이븐폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1292', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f9cc4ae6-98e8-4e48-8d4c-f95ead85ca20', '와글와글체', 'WaggleWaggle', 'WaggleWaggle', 'decorative', '와글와글체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1294', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd238c1b7-108d-42ca-80a0-cefe8ac01aa9', '학교안심 돋보기', 'SchoolSafetyMagnifier', 'SchoolSafetyMagnifier', 'decorative', '학교안심 돋보기폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1295', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c9c226a3-18d5-4992-962b-a0da8408e69d', '학교안심 은하수', 'SchoolSafetyMilkyWay', 'SchoolSafetyMilkyWay', 'decorative', '학교안심 은하수폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1296', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0e6d3dc3-6b17-4a03-b5b8-4e4f510bda06', '학교안심 구름', 'SchoolSafetyCloud', 'SchoolSafetyCloud', 'decorative', '학교안심 구름폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1297', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '65d8f9ee-a36c-49cb-b988-a732593e6856', '학교안심 점심시간', 'SchoolSafeLunchtime', 'SchoolSafeLunchtime', 'decorative', '학교안심 점심시간폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1298', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8e760a61-9b1d-4d6a-92f8-58f8a903e23a', '학교안심 지우개', 'SchoolSafetyEraser', 'SchoolSafetyEraser', 'decorative', '학교안심 지우개폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1299', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '7da9d5f2-f717-418f-a51f-97a3b014f7b4', '경기천년바탕', 'GyeonggiMillenniumBackground', 'GyeonggiMillenniumBackground', 'serif', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/13', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c083c956-e897-49d7-b370-35294ebb3cbb', '학교안심 꼬꼬마', 'SchoolSafeLittleOne', 'SchoolSafeLittleOne', 'decorative', '학교안심 꼬꼬마폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1300', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'daf22c28-d032-474d-bd0b-ee92613c93e3', '학교안심 꽈배기', 'SchoolSafeTwist', 'SchoolSafeTwist', 'decorative', '학교안심 꽈배기폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1301', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd161e33f-db31-4556-9e30-ef49da38ad28', '학교안심 콧수염', 'SchoolSafetyMustache', 'SchoolSafetyMustache', 'decorative', '학교안심 콧수염폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1302', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1c594bee-35b4-46c7-a42a-331a841fdf99', '학교안심 마법사', 'SchoolSafetyWizard', 'SchoolSafetyWizard', 'decorative', '학교안심 마법사폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1303', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '03225b38-cb7f-4b8e-916c-662d8142221e', '학교안심 모험가', 'SchoolSafeAdventurer', 'SchoolSafeAdventurer', 'decorative', '학교안심 모험가폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1304', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '611eba00-3d6e-4372-8e18-a94d035296fd', '학교안심 몽글몽글', 'SchoolSafeMonggleMonggle', 'SchoolSafeMonggleMonggle', 'decorative', '학교안심 몽글몽글폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1306', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2b33a2ea-589c-4b8b-8d1d-5bd704162a33', '학교안심 물결', 'SchoolSafetyWave', 'SchoolSafetyWave', 'decorative', '학교안심 물결폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1307', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '41e58346-98a9-49b8-9df3-45a99faff8d3', '학교안심 나무', 'SchoolSafeTree', 'SchoolSafeTree', 'decorative', '학교안심 나무폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1309', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '3fc98b4a-6c11-43e7-a0f0-e4564a5de2f3', '학교안심 리코더', 'SchoolSafetyRecorder', 'SchoolSafetyRecorder', 'decorative', '학교안심 리코더폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1311', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c525c688-cc59-4030-b625-b17feb14f2ef', '학교안심 사물함', 'SchoolSafeLocker', 'SchoolSafeLocker', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1312', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '190341b8-80ea-4e4e-adf1-c01688536892', '학교안심 소나기', 'SchoolSafetyShower', 'SchoolSafetyShower', 'decorative', '학교안심 소나기폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1313', NULL, 0, true, false, NOW(), NOW() );
