-- font_families 배치 12

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6d191281-5b1c-4b4e-b89b-4bbf6804a267', '망고보드 별별체', 'MangoBoardByeolbyeol', 'MangoBoardByeolbyeol', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1404', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'bfe752ce-d09d-4f9a-bbbf-038a0cd58df4', '망고보드 또박체', 'MangoBoardTtobaks', 'MangoBoardTtobaks', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1405', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a90c3a63-1868-46ff-a2b9-1f42ff717781', '어비 똘영체', 'AebiTtolYeong', 'AebiTtolYeong', 'decorative', '어비 똘영체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/141', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a5d8703f-76a4-4b34-a94b-a2a7cd7539f6', '어비 또요체', 'AviTtoy', 'AviTtoy', 'decorative', '어비 또요체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/142', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '259a0691-2f00-49e8-9b9b-90c5f88ecf41', '한컴 훈민정음', 'HancomHunminjeongeum', 'HancomHunminjeongeum', 'decorative', '한컴 훈민정음폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1420', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '51920d5d-caf9-4232-8c5a-1f81eaf7e19d', '한컴 말랑말랑', 'HancomMalrangmalrang', 'HancomMalrangmalrang', 'decorative', '한컴 말랑말랑폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1421', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'feaa5b34-49e6-44d5-9c2a-e82d1e076b9a', '한컴 산스', 'HancomSans', 'HancomSans', 'gothic', '한컴 산스폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1423', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '4bf5eaaf-210b-40ef-99db-d7330614a529', '온글잎 빈수체', 'OngleipBinsuche', 'OngleipBinsuche', 'decorative', '온글잎 빈수체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1425', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b2ccbafe-90e8-4b49-9ac8-069e2c0f36aa', '온글잎 언즈체', 'OngleipUnz', 'OngleipUnz', 'decorative', '온글잎 언즈체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1426', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b04e63c5-708e-4416-8897-2ec808d7cc8c', '어비 동경체', 'AbiDonggyeong', 'AbiDonggyeong', 'decorative', '어비 동경체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/143', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1d621ec1-08d4-43ff-8316-ef3c7f87e12d', '윤초록우산어린이 만세', 'YoonChoWooSan', 'YoonChoWooSan', 'decorative', '윤초록우산어린이 만세폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1431', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0f3c59a2-6e33-42de-ab04-bf4ca9c13067', '윤초록우산어린이 민국', 'YunChorokwoosanEoriniMinguk', 'YunChorokwoosanEoriniMinguk', 'decorative', '윤초록우산어린이 민국폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1432', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '841133d1-4534-4ab8-b911-7f287dc9b7f2', '윤초록우산어린이 대한', 'YoonchoUsanChildrenS', 'YoonchoUsanChildrenS', 'decorative', '윤초록우산어린이 대한폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1433', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '514c6c3f-868a-466b-8ff6-1745a7c71da9', '오케이티콘체', 'Okticon', 'Okticon', 'decorative', '오케이티콘체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1434', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e5276c12-42d5-48c3-94af-08e29322af30', '온글잎 김콩해', 'OngleipKimkonghae', 'OngleipKimkonghae', 'decorative', '온글잎 김콩해폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1437', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd3b483c3-10cd-42f2-b5eb-45743883b314', '온글잎 지우쏘낭', 'OngleipJiuSsoNang', 'OngleipJiuSsoNang', 'decorative', '온글잎 지우쏘낭폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1438', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c9e2e047-8561-458d-9c61-d0e55caad1e5', '온글잎 승훈체', 'OngleipSeunghun', 'OngleipSeunghun', 'decorative', '온글잎 승훈체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1439', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0f699712-d8bb-40d8-b6cd-4955f98dfe83', '어비 둘둘체', 'Avivi22', 'Avivi22', 'decorative', '어비 둘둘체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/144', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e17c609b-7723-41a1-9107-c0ead4bf32f2', '구름 산스 코드', 'CloudSansCode', 'CloudSansCode', 'gothic', '구름 산스 코드폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1445', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8d0830d8-9dc2-4dca-ac5c-a57bec8e0377', '구름 산스', 'CloudSans', 'CloudSans', 'gothic', '구름 산스폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1446', NULL, 0, true, false, NOW(), NOW() );
