-- font_families 배치 5

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b24e635e-7f5e-4f1a-ab6c-e98dbf557ce4', '한글재민체3.0', 'HangulJaemin30', 'HangulJaemin30', 'decorative', '한글재민체3.0폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1177', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b9b5e8e0-f0fe-4539-bd92-b796d5fcc0cf', 'Intel One Mono Italic', 'IntelOneMonoItalic', 'IntelOneMonoItalic', 'monospace', 'Intel One Mono Italic폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1178', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'bd061eb3-71af-462c-8c66-6347bc988273', '넷마블체', 'Netmarble', 'Netmarble', 'decorative', '넷마블체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/118', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '44266333-9cb9-4538-a8a6-39adcfb0438f', 'Intel One Mono', 'IntelOneMono', 'IntelOneMono', 'monospace', 'Intel One Mono폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1182', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'dc419447-8b16-4864-aaed-ca6a00c752da', '파셜산스', 'PartialSans', 'PartialSans', 'gothic', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1186', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f936f66a-abb3-472d-928f-5d75054c9c1a', '램체', 'Ram', 'Ram', 'decorative', '램체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1188', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c24d3155-588b-45ec-8a74-44fd320195b2', '신영복체', 'ShinYoungbok', 'ShinYoungbok', 'decorative', '신영복체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/119', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c9d73e20-0e3e-4899-8c46-b934f0a9b7e0', '60’s STRIPE', '60SStripe', '60SStripe', 'decorative', '60’s STRIPE폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1193', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e00110be-caa0-4884-a109-d8aca2d4fab3', 'BOKEH', 'Bokeh', 'Bokeh', 'decorative', 'BOKEH폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1194', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5f8712be-438b-4ea5-8a43-19575d45d6b4', '카페24슈퍼매직', 'Cafe24SuperMagic', 'Cafe24SuperMagic', 'decorative', '카페24슈퍼매직폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1195', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b90c4691-bc7b-4b59-a2d3-f5ebbf7a36c9', 'CROOKED', 'Crooked', 'Crooked', 'decorative', 'CROOKED폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1197', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '9e20b5d3-4d9e-4646-b497-ce19ec3d6fd4', 'DeltaUniverse', 'DeltaUniverse', 'DeltaUniverse', 'decorative', 'DeltaUniverse폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1198', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '008fb3a1-c231-47cf-a31f-05abc3c8858f', '강원특별자치도체', 'GangwonSpecialSelfGoverningProvince', 'GangwonSpecialSelfGoverningProvince', 'decorative', '강원특별자치도체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1199', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e66e5f71-e970-42e5-b505-76d5aac04baf', 'KBIZ한마음명조체', 'KbizHanmaumMyungjo', 'KbizHanmaumMyungjo', 'serif', 'KBIZ한마음명조체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/12', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'efa463dd-3b0f-4fb9-8841-803aaca019c6', '애터미체', 'Atomy', 'Atomy', 'decorative', '애터미체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/120', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '63f9d15f-df6c-4af1-ad5b-fb328d3627b7', '학교안심 바른바탕', 'SchoolSafetyFoundation', 'SchoolSafetyFoundation', 'serif', '디자인 210랑 비슷한 무료 폰트 있을까요? ㅜㅜ 날카로운 느낌보단 부드럽게 사용 가능한 명조 폰트...!!!!!', '사용 가능', 'https://noonnu.cc/font_page/1200', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5ec112fe-c18c-47af-9e69-ced677f3dfcd', '학교안심 바른돋움', 'SchoolSafetyGoodSupport', 'SchoolSafetyGoodSupport', 'decorative', '학교안심 바른돋움폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1202', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1e4d5a1d-0677-4274-beeb-2aa503fe2ad2', '학교안심 봄방학', 'SchoolSafetySpringBreak', 'SchoolSafetySpringBreak', 'decorative', '제스트광고디자인', '사용 가능', 'https://noonnu.cc/font_page/1204', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '59d3541d-281b-41dd-b1e6-9afe81aa833f', '학교안심 분필', 'SchoolSafetyChalk', 'SchoolSafetyChalk', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1205', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5e958983-638f-46da-833e-95bb77cc8028', '학교안심 붓펜', 'SchoolSafetyBrushPen', 'SchoolSafetyBrushPen', 'handwriting', '학교안심 붓펜폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1206', NULL, 0, true, false, NOW(), NOW() );
