-- font_families 배치 17

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c1cd6f70-197c-4418-a9ae-2f97dd2d9903', '어비 찌빠빠체', 'AviCzippapa', 'AviCzippapa', 'decorative', '어비 찌빠빠체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/160', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a6d6ecde-d5ed-470c-b37e-dd57fbb6225e', '서울알림체', 'SeoulNotice', 'SeoulNotice', 'decorative', '서울알림체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1604', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '55dd400b-567a-45e7-828b-634bcac53d95', '굵은둥근모', 'BoldRound', 'BoldRound', 'decorative', '굵은둥근모폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1606', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'db2a9a19-a933-4bab-a625-11d9444dcb16', '엑큐', 'Xcu', 'Xcu', 'decorative', '엑큐폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1607', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '08e3cef6-ec3b-4d4a-9f00-e3da88589125', '갈무리11 Condensed', 'Galmuri11Condensed', 'Galmuri11Condensed', 'decorative', '갈무리11 Condensed폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1609', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1edd3c6b-703a-4866-9da7-bbb9159e464e', '어비 찌풍딩체', 'AbiJjifungding', 'AbiJjifungding', 'decorative', '어비 찌풍딩체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/161', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2c698751-4f17-4d92-a680-3047a82ed48a', '갈무리14', 'Galmuri14', 'Galmuri14', 'decorative', '갈무리14폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1610', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '698a393d-f8ea-411e-ae40-95f07555982a', 'LanaPixel', 'Lanapixel', 'Lanapixel', 'decorative', 'LanaPixel폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1611', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0c85de98-9a69-4fa1-af42-7a74db0805c2', 'PF스타더스트 3.0', 'PfStardust30', 'PfStardust30', 'decorative', 'PF스타더스트 3.0폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1614', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'add11db8-c2ed-4952-aac0-dc5826085c67', 'PF스타더스트 3.0 S', 'PfStardust30S', 'PfStardust30S', 'decorative', 'PF스타더스트 3.0 S폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1615', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f957fc44-2336-44f6-aff5-693e02be52ab', '사천항공체', 'Sacheonhanggong', 'Sacheonhanggong', 'decorative', '사천항공체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1618', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '04bf959f-b22f-45b5-b48d-ffd595110d42', '사천우주체', 'SacheonUniverse', 'SacheonUniverse', 'decorative', '사천우주체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1619', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '115c7157-e06f-4226-a464-b32fef80f6a5', '어비 조커체', 'AviJoker', 'AviJoker', 'decorative', '어비 조커체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/162', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '118f4e35-1f15-4172-9cbb-1a33ef9c1343', '유나의 화요일', 'YunaSTuesday', 'YunaSTuesday', 'decorative', '유나의 화요일폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1620', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '244db45e-c7b2-4907-83d9-c92230531be0', '카페24 PRO UP', 'Cafe24ProUp', 'Cafe24ProUp', 'decorative', '카페24 PRO UP폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1621', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '17eccedb-8889-42c1-bd53-1e88229bc426', '은평사가독서체', 'EunpyeongSagaDokseo', 'EunpyeongSagaDokseo', 'decorative', '은평사가독서체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1623', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f43e3a9d-f27b-4613-ab65-505e409ad4d8', '그리운 김정원', 'KimJeongWonSMiss', 'KimJeongWonSMiss', 'decorative', '그리운 김정원폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1624', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2b7f570f-0e0a-4613-93fa-a04968b5ab64', '한글재민체 6.0', 'HangulJaemin60', 'HangulJaemin60', 'decorative', '한글재민체 6.0폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1625', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '802ae6cf-0054-429c-99d8-5be2f88f6aea', '어비 쩡체', 'AbiJjeong', 'AbiJjeong', 'decorative', '어비 쩡체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/163', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '33987d3c-2903-467c-8dcc-ffb33d8f2901', '교보손글씨 2024 박서우', 'KyoboHandwriting2024SeoWooPark', 'KyoboHandwriting2024SeoWooPark', 'handwriting', '교보손글씨 2024 박서우폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1638', NULL, 0, true, false, NOW(), NOW() );
