-- font_families 배치 3

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2de5e201-f0a4-47b8-bc94-51579490a5a1', 'KCC박경리체', 'KccParkGyeongni', 'KccParkGyeongni', 'decorative', 'KCC박경리체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1099', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5c9b079a-b476-4941-928d-9d3c8dba82c5', 'KBIZ한마음고딕체', 'KbizHanmaumGothic', 'KbizHanmaumGothic', 'gothic', 'KBIZ한마음고딕체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/11', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '7f492755-6634-4dbd-b2f2-79e1823d6b3e', '롯데리아 촵땡겨체', 'LotteriaChwapttaenggyeo', 'LotteriaChwapttaenggyeo', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1100', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6aeeccfe-4efc-47cd-8d30-0dc47a8ad477', '롯데리아 딱붙어체', 'Lotteria', 'Lotteria', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1101', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0d332bf0-4f6d-46cc-8807-b438df1247ba', 'Neo둥근고딕Pro', 'NeoDunggeunGothicPro', 'NeoDunggeunGothicPro', 'gothic', 'Neo둥근고딕Pro폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1102', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '72f4c099-6c9d-46d7-b211-446b28dfe84a', '오아고딕', 'Oagothic', 'Oagothic', 'gothic', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1103', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'cb2a26fc-d5bb-4575-82f0-09de9d8bcb5b', 'Rix할매의꽃담요', 'RixGrandmaSFlowerBlanket', 'RixGrandmaSFlowerBlanket', 'decorative', 'Rix할매의꽃담요폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1106', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd3cabbc7-7607-4eb5-ae4b-bc22cc6c69cb', '태백 은하수체', 'TaebaekGalaxy', 'TaebaekGalaxy', 'decorative', '태백 은하수체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1107', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '4c53beac-d1b3-40ed-b5b2-22a802a6e159', '둘기마요고딕', 'DoolgiMayoGothic', 'DoolgiMayoGothic', 'gothic', '둘기마요고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1108', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '9b597d1f-c668-426e-928c-f388a9d62c1b', 'Yoon 하이멜로디', 'Yoon 하이멜로디', 'Hi Melody', 'decorative', 'Yoon 하이멜로디폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1109', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '76e9bace-0fc5-4575-a012-51b36337ad4c', 'Yoon 감자꽃', 'Yoon 감자꽃', 'Gamja Flower', 'decorative', '캡컷에 있는 아기 라는 폰트인데 유튜브 영상 제작하는데 사용해도 될까요?', '사용 가능', 'https://noonnu.cc/font_page/1110', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a940b06b-c2fc-42d3-89f4-bb424bad2d8f', 'DX단하루', 'DX단하루', 'Single Day', 'decorative', 'DX단하루폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1111', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'ecdfc6c1-117c-4565-a954-ef71445c3109', '긱블 말랑이체', 'GeekbleMalrangiche', 'GeekbleMalrangiche', 'decorative', '긱블 말랑이체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1113', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e4d163f5-ef7f-44e9-88cb-aef48fc76b12', '김정철고딕', 'KimJeongCheolGothic', 'KimJeongCheolGothic', 'gothic', '김정철고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1114', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '207b0ec9-13a2-427d-b626-7e27f5f85270', '김정철명조', 'KimJeongcheolMyoungjo', 'KimJeongcheolMyoungjo', 'serif', '김정철명조폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1117', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd52da23a-8292-44dc-adc7-b6f9cc44b3bf', 'sn별별정직', 'SnByulbyuljeongjik', 'SnByulbyuljeongjik', 'decorative', 'sn별별정직폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/112', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1660962b-2ed4-44e8-9057-dd74acb95cf8', '김정철손글씨', 'KimJeongCheolHandwriting', 'KimJeongCheolHandwriting', 'handwriting', '김정철손글씨폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1120', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1311629a-eb30-40f0-8913-ea2ffc3af9ae', '한나체 Air', 'HannaAir', 'HannaAir', 'decorative', '한나체 Air폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/113', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e2d3a900-ed38-4a71-868c-c767960af219', '116앵덕정직', '116Angdeokjeongjik', '116Angdeokjeongjik', 'decorative', '116앵덕정직폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1131', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a6a97840-1fc9-404e-9288-2d011ff1b5fb', '고령딸기체', 'GoryeongStrawberry', 'GoryeongStrawberry', 'decorative', '자막 디자인을 공부하는데 저걸 일일이 그렸을 것 같지는 않아 혹시나 폰트자체가 저런게 있나 싶어 질문드리러 왔습니다 ㅠㅠ', '사용 가능', 'https://noonnu.cc/font_page/1132', NULL, 0, true, false, NOW(), NOW() );
