-- font_families 배치 14

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5abcc8a4-2f2c-4642-b677-f5370d6c0202', '학교안심 퍼즐 블랙', 'SchoolSafetyPuzzleBlack', 'SchoolSafetyPuzzleBlack', 'decorative', '이거 무슨 폰트인가요? (사진 출처: 모찌엘님)', '사용 가능', 'https://noonnu.cc/font_page/1484', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c13cba8b-5375-457c-94b1-9dbf0df9c64e', '학교안심 퍼즐 아웃라인', 'SchoolSafetyPuzzleOutline', 'SchoolSafetyPuzzleOutline', 'decorative', '학교안심 퍼즐 아웃라인폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1485', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '39cfb27f-d37c-42fa-8864-fd25f30fd38a', 'DEPARTURE_MONO', 'DepartureMono', 'DepartureMono', 'monospace', 'DEPARTURE_MONO폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1487', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b70ff487-d25d-413e-9ed9-267152d53909', '어비 햄체', 'AviHam', 'AviHam', 'decorative', '어비 햄체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/149', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6ecfbbcf-0e1e-4a54-a0d0-c640717bbc70', 'EVECondom', 'Evecondom', 'Evecondom', 'decorative', 'EVECondom폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1491', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b88ebfec-bd42-4405-92cd-556c5349d6bb', '가비아 고스란체', 'GabiaGosranche', 'GabiaGosranche', 'decorative', '가비아 고스란체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1492', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'adc259b2-a9c6-4fb0-8c7e-c61fa584891e', '가비아 눌체', 'GabiaNul', 'GabiaNul', 'decorative', '가비아 눌체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1493', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '827af545-fc14-45b7-8a81-7c3cba9bd5b9', '숙명눈꽃체', 'Sukmyung', 'Sukmyung', 'decorative', '숙명눈꽃체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1494', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'bbc6c73a-303c-44b2-a45f-105ab9c608bc', '눈누 기초고딕', 'NoonnuBasicGothic', 'NoonnuBasicGothic', 'gothic', '눈누 기초고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1496', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '96afaf81-3b73-4c44-94f2-4697cb1e2047', '가물치 무료고딕', 'GamulchiFreeGothic', 'GamulchiFreeGothic', 'gothic', '가물치 무료고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1499', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b7473f37-90ea-4a0a-8099-5128ffc85dd4', '아리따돋움', 'ArittaDodum', 'ArittaDodum', 'decorative', '아리따돋움폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/15', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2612049e-8608-4d6a-8901-7023c913e185', '어비 한비', 'EobiHanbi', 'EobiHanbi', 'decorative', '어비 한비폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/150', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'bf857334-10cb-4751-8129-e60a0c6bb022', '꾸불림체', 'KkuBulLim', 'KkuBulLim', 'decorative', '꾸불림체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1500', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '298e50d9-04b1-4ea2-adff-c970c3a2d59a', '보배섬진도체', 'Bobaesomjindo', 'Bobaesomjindo', 'decorative', '보배섬진도체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1501', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1ca7d257-e2c2-43ad-89f2-6fde34bac7e3', 'Cafe24 Nyangi Black', 'Cafe24NyangiBlack', 'Cafe24NyangiBlack', 'decorative', 'Cafe24 Nyangi Black폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1502', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6a73c72c-7a5e-4805-a234-e1a2db8fc5fd', 'Cafe24 Nyangi White', 'Cafe24NyangiWhite', 'Cafe24NyangiWhite', 'decorative', 'Cafe24 Nyangi White폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1503', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '24e48b6f-1d64-4e6e-a2d9-4625fdc071a3', '플라이트 산스', 'FlightSans', 'FlightSans', 'gothic', '플라이트 산스폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1504', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '7a63db7b-c238-4886-a135-f6006709cd1e', '플라이트 산스 Title', 'FlightSansTitle', 'FlightSansTitle', 'gothic', '플라이트 산스 Title폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1506', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f7355d73-9ed9-4af6-86dc-900a800f9f73', '구미돋움체', 'GumiDodum', 'GumiDodum', 'decorative', '구미돋움체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1507', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c097d420-30bf-435d-86cb-a0928469aa74', '구미첨단산업체', 'GumiAdvancedIndustrialComplex', 'GumiAdvancedIndustrialComplex', 'decorative', '구미첨단산업체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1508', NULL, 0, true, false, NOW(), NOW() );
