-- font_families 배치 18

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'bf164047-c710-470e-9381-e900c4fe7ecc', '프박 뽑았체', 'PpObBat', 'PpObBat', 'decorative', '프박 뽑았체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1639', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '821a4a8b-485e-4f5a-80f5-fd6ea8664f54', '어비 카이루체', 'AbeeKai', 'AbeeKai', 'decorative', '어비 카이루체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/164', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '49f0151a-d3a7-4799-a6fe-a2768c74dffd', '하늘내린 인제체', 'HaneulnaerinInje', 'HaneulnaerinInje', 'decorative', '하늘내린 인제체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1642', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8a8b1939-399b-47d9-b895-9f8f8e9a09ad', '온글잎 대롱체', 'OnglippDaelong', 'OnglippDaelong', 'decorative', '온글잎 대롱체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1644', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '3d7d0c7a-7d02-4b24-b82f-bae06ce7872e', '영월체', 'Yeongwol', 'Yeongwol', 'decorative', '영월체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1648', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'ef21e088-7035-467c-964b-6555f33a41fc', '나눔명조옛한글', 'NanumMyeongjoOldHangeul', 'NanumMyeongjoOldHangeul', 'serif', '나눔명조옛한글폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1649', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '396bae1c-a66c-472d-ad01-0b6671e25ddb', '어비 카이루장난체', 'AviKailujangnan', 'AviKailujangnan', 'decorative', '어비 카이루장난체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/165', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '40350b2d-d918-4942-b4cc-b56b8b6d82b9', '나눔바른고딕옛한글', 'NanumBareunGothicOldHangeul', 'NanumBareunGothicOldHangeul', 'gothic', '나눔바른고딕옛한글폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1650', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd278da42-77b3-4361-bcc9-cb492bfeaa92', '나눔고딕에코', 'NanumGothicEco', 'NanumGothicEco', 'gothic', '나눔고딕에코폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1651', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '0ee8e0d5-849b-49e0-a1ab-025c69903975', '나눔명조에코', 'NanumMyeongjoEco', 'NanumMyeongjoEco', 'serif', '나눔명조에코폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1652', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'dfcea1ab-c282-4092-a9c8-cdaad6c28649', '그리운 사막의 연우체', 'NostalgicDesertYeonwoo', 'NostalgicDesertYeonwoo', 'decorative', '그리운 사막의 연우체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1654', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '506045f2-9055-433b-8051-eb46deabf23c', '학교안심 반달', 'SchoolSafetyHalfMoon', 'SchoolSafetyHalfMoon', 'decorative', '학교안심 반달폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1656', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '4c27d4cb-d184-47c1-acb6-25ea20a5b262', '학교안심 어항꾸미기', 'SchoolSafetyAquariumDecor', 'SchoolSafetyAquariumDecor', 'decorative', '학교안심 어항꾸미기폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1657', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '3a525b9c-b348-48fb-a019-53a7f37264db', '학교안심 자연', 'SchoolPeaceOfMindNature', 'SchoolPeaceOfMindNature', 'decorative', '학교안심 자연폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1658', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2c90f667-85f0-4892-bb25-182f2dc99d9b', '학교안심 자유시간', 'SchoolSafetyFreeTime', 'SchoolSafetyFreeTime', 'decorative', '학교안심 자유시간폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1659', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'ace0866b-51ce-47b8-b0a7-aa7752a5851b', '어비 깡자체', 'EobiKkangja', 'EobiKkangja', 'decorative', '어비 깡자체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/166', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '9d809b59-81c7-4baa-9642-f0277e802fbf', '학교안심 몽당분필', 'SchoolSafetyStubbyChalk', 'SchoolSafetyStubbyChalk', 'decorative', '학교안심 몽당분필폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1660', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '91f6ee9a-2054-46a3-8150-bd247b536bae', '학교안심 시간표', 'SchoolSafetySchedule', 'SchoolSafetySchedule', 'decorative', '학교안심 시간표폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1661', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '15ca997e-a946-4979-9b9a-35ca2925c3a0', '학교안심 수수깡', 'SchoolSafetySusukkang', 'SchoolSafetySusukkang', 'decorative', '학교안심 수수깡폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1662', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '251646b2-168a-447d-8ba4-3f2936b785d9', '콜디웹툰메이커 온글잎 폰트', 'KoldiWebtoonMakerOngleifFont', 'KoldiWebtoonMakerOngleifFont', 'decorative', '콜디웹툰메이커 온글잎 폰트폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1665', NULL, 0, true, false, NOW(), NOW() );
