-- font_families 배치 7

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'af3b7808-e3d6-408e-9c69-1e9595376b18', '헬스셋 조릿대체', 'HealthsetJoritdae', 'HealthsetJoritdae', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/124', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2539ad47-4526-4029-9b7b-f2bb3fc91057', 'Orbit', 'Orbit', 'Orbit', 'decorative', 'Orbit폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1242', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8754f6d5-45d3-44d1-9946-1cf08bcbacb9', '소요단풍체', 'SoyoDanpung', 'SoyoDanpung', 'decorative', '소요단풍체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1244', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '42cfbad8-0fb2-4c96-80f0-7e6372e25a52', '태백체', 'Taebaek', 'Taebaek', 'decorative', '태백체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1246', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8c6cf437-4588-4406-a326-1fa72e70760f', '태백은하수체', 'TaebaekMilkyWay', 'TaebaekMilkyWay', 'decorative', '태백은하수체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1247', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '79b8a569-2cf6-468d-a662-765905262c89', '영주풍기인삼체', 'YeongjuPunggiGinseng', 'YeongjuPunggiGinseng', 'decorative', '영주풍기인삼체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1248', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '238cfd02-78a2-4e55-90d0-0344531de05d', '카페24 모야모야 Face', 'Cafe24MoyaMoyaFace', 'Cafe24MoyaMoyaFace', 'decorative', '카페24 모야모야 Face폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1249', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd26cbcc2-e558-4591-9063-975777c74301', '카페24 모야모야', 'Cafe24MoyaMoya', 'Cafe24MoyaMoya', 'decorative', '카페24 모야모야폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1250', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '139833b7-9594-4aa3-ab9d-02d5ac0ae13c', '이스타체', 'Easta', 'Easta', 'decorative', '이스타체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1251', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '6d84f31a-e4c5-4641-ae1f-7d5562c391fc', '신동엽 손글씨', 'ShinDongYeopHandwriting', 'ShinDongYeopHandwriting', 'handwriting', '신동엽 손글씨폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1259', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '76a4b22c-a600-4436-81c0-0800a32124c9', '헬스셋 고딕체', 'HealthsetGothic', 'HealthsetGothic', 'gothic', '헬스셋 고딕체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/126', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '3e87fef3-5c60-482e-a972-e25ac1f9ff1d', '정림사지', 'JeongnimsaJi', 'JeongnimsaJi', 'decorative', '정림사지폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1261', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f2c62144-8fe8-43c3-9d7c-2c7cfb756754', 'Y클로버체', 'YClover', 'YClover', 'decorative', 'Y클로버체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1265', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '227c35a0-62cd-4db6-88ff-ab6f6aa27a32', '충주김생체', 'ChungjuKimsaeng', 'ChungjuKimsaeng', 'decorative', '충주김생체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1277', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '036eca7b-7804-42f1-815e-bc51fa55033d', '대암 이태준체', 'DaeAmLeeTaeJun', 'DaeAmLeeTaeJun', 'decorative', '대암 이태준체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1278', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '396c4482-2c76-4347-acf0-21c20bdf6aa2', '넥슨 카트 고딕', 'NexonCartGothic', 'NexonCartGothic', 'gothic', '넥슨 카트 고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1284', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '69736be6-e99b-4896-a4cc-d2d05580dba5', '경북대진리체', 'GyeongbukDaeJinri', 'GyeongbukDaeJinri', 'decorative', '경북대진리체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1286', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '42cad197-9ea6-4026-87b9-ab42a5836be2', 'OG 르네상스 비밀', 'OgRenaissanceSecret', 'OgRenaissanceSecret', 'decorative', 'OG 르네상스 비밀폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1287', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5f17ff95-9f24-4a51-aa2b-53ab19db1b5e', '세종병원체', 'SejongHospital', 'SejongHospital', 'decorative', '세종병원체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1288', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'ccb3721e-399d-4418-ba7f-f23b57368ba6', '시원한 설레임체', 'SiwonhanSeolreim', 'SiwonhanSeolreim', 'decorative', '시원한 설레임체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1290', NULL, 0, true, false, NOW(), NOW() );
