-- font_families 배치 37

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5bf3ec82-ef98-4bab-945d-3ed4154e86e7', '나는야핵인싸체 최서연', 'NaneunyaHaegInssaChoiSeoyeon', 'NaneunyaHaegInssaChoiSeoyeon', 'decorative', '나는야핵인싸체 최서연폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/774', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a5ee0130-e95f-4611-bb98-147bb52126b0', 'notcliche체 이현준', 'NotclicheHyeonjunLee', 'NotclicheHyeonjunLee', 'decorative', 'notcliche체 이현준폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/775', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '03976858-359c-409b-9253-e2d2405ae3da', '설립체 유건욱', 'FounderYooGeonWook', 'FounderYooGeonWook', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/776', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'd45b5380-7e9c-4009-bd60-04de52ff27a3', '칠백삼체 유서연', '700SansYusoryeon', '700SansYusoryeon', 'decorative', '칠백삼체 유서연폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/777', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '9023e087-5c5a-44aa-8ffb-8ab0ed347ea9', '가시가시체 백민주', 'GasiGasiBaekMinju', 'GasiGasiBaekMinju', 'decorative', '가시가시체 백민주폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/778', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b845780b-93fe-4759-aabf-00af5fe18a51', 'EBS주시경체', 'EbsJushigyeong', 'EbsJushigyeong', 'decorative', 'EBS주시경체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/78', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '69f1806c-a119-418d-abc3-2177448faa48', '교보손글씨 2020 박도연', 'KyoboHandwriting2020ParkDoYeon', 'KyoboHandwriting2020ParkDoYeon', 'handwriting', '교보손글씨 2020 박도연폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/782', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '644a0a13-6ea8-4558-9074-f1b175b26154', '상주다정다감체', 'SangjuDajeongdagam', 'SangjuDajeongdagam', 'decorative', '상주다정다감체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/783', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '738144bf-eed3-43ae-873a-3fe8e7db16c2', '상주경천섬체', 'SangjuGyeongcheonseom', 'SangjuGyeongcheonseom', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/784', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '220dadfb-5663-404e-b3f9-c012c1d05dca', '상주해례본체', 'SangjuHaerebon', 'SangjuHaerebon', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/785', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c1fd46fc-d06d-4bd3-9b98-83948ffc9235', '상주곶감체', 'SangjuGotgam', 'SangjuGotgam', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/786', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '5bddafdd-a33e-487a-be98-04dc222f1ed5', 'ACC 어린이 하늘맑은체', 'AccChildrenSSkyClear', 'AccChildrenSSkyClear', 'decorative', 'ACC 어린이 하늘맑은체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/787', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '48fd316d-3ce0-40ad-b225-896e9715d46b', 'ACC 어린이 마음고운체', 'AccChildrenSKindHeart', 'AccChildrenSKindHeart', 'decorative', 'ACC 어린이 마음고운체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/788', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '757042db-bbe2-495f-a77e-6a1b27dafa5b', 'ACC 어린이 가을담은체', 'AccChildrenSFall', 'AccChildrenSFall', 'decorative', 'ACC 어린이 가을담은체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/789', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '054c1912-17ff-45f8-a90a-2111bb9c3fe0', '고양체', 'Goyang', 'Goyang', 'decorative', '고양체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/79', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '03db6b6f-adac-4e69-9b5e-d962e04a3974', '팔칠엠엠 일상 기울임', 'PalchilmmDailyItalic', 'PalchilmmDailyItalic', 'decorative', '팔칠엠엠 일상 기울임폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/790', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '127cd376-cbd3-49ac-b98e-8a69a38798ea', '팔칠엠엠 일상 보통', '87mmDailyRegular', '87mmDailyRegular', 'decorative', '팔칠엠엠 일상 보통폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/791', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8c3d97ab-e88d-4ffd-9589-22b39b55ba1e', 'Y유니버스체', 'YUniverse', 'YUniverse', 'decorative', 'Y유니버스체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/792', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '8c228c33-c564-46e2-a269-245396e3f8d2', 'KITA', 'Kita', 'Kita', 'decorative', 'KITA폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/794', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'afe2fa6c-e6bd-460d-a52f-faa2ea7523a0', '고양덕양체', 'GoyangDeokyang', 'GoyangDeokyang', 'decorative', '고양덕양체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/80', NULL, 0, true, false, NOW(), NOW() );
