-- font_families 배치 10

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '2b708b9a-9e6c-48ba-a010-59986796b35b', '어비 바니나니체', 'AbiBaninani', 'AbiBaninani', 'decorative', '어비 바니나니체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/135', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1b2067b6-e88b-4a2a-8da7-e86019a13f24', '쿨가이', 'CoolGuy', 'CoolGuy', 'decorative', '쿨가이폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1350', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '9de9fc87-eb39-4555-b7d3-709145ad7156', '온글잎 매일옥자체', 'OngleipMaeilokjache', 'OngleipMaeilokjache', 'decorative', '온글잎 매일옥자체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1351', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '36984582-12c7-4d7f-a169-f822344c1ffc', '온글잎 메모앤옥자체', 'OngleipMemoOkja', 'OngleipMemoOkja', 'decorative', '온글잎 메모앤옥자체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1352', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '641f95fb-cf20-4584-9733-e6c94e128e34', '와구리체', 'Waguri', 'Waguri', 'decorative', '와구리체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1353', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f0d4e3d8-b96c-466e-a25a-a49f6b872b0c', '영주선비체', 'YeongjuSeonbi', 'YeongjuSeonbi', 'decorative', '영주선비체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1355', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1935a993-a0ac-4030-b672-3d8bb0ccb03d', 'KCC한빛체', 'KccHanbit', 'KccHanbit', 'decorative', 'KCC한빛체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1358', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1c1df195-8ef7-431f-8b3d-b5d90044f6d3', '런드리고딕', 'LaundryGothic', 'LaundryGothic', 'gothic', '런드리고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1359', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'afdd35dc-4c5b-464e-a7c6-0d95a58544e1', '어비 버찌체', 'AviBurjiche', 'AviBurjiche', 'decorative', '어비 버찌체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/136', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c5cb1d1b-5f70-486b-bf01-6eb0c2015bdd', '프리젠테이션', 'Presentation', 'Presentation', 'decorative', '프리젠테이션폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1369', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '46734aec-2499-4919-bbb7-811bca91ad21', '어비 봉식이체', 'AebiBongsik', 'AebiBongsik', 'decorative', '어비 봉식이체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/137', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'f018962a-07ba-42f5-b899-0978539668a0', '웨이브 파도체', 'Wave', 'Wave', 'decorative', '웨이브 파도체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1370', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '07ccbbdc-f3d6-4760-b916-3be59d0dd673', '사월십육일체 생명', 'April16thLife', 'April16thLife', 'decorative', '사월십육일체 생명폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1371', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '12c528c8-72bc-4c34-b253-4085436b9f71', '사월십육일체 안전', 'April16thSafety', 'April16thSafety', 'decorative', '사월십육일체 안전폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1372', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '91d6fb45-8a6c-4828-b5ee-97da0aa1fdb3', '사월십육일체 약속', 'April16Promise', 'April16Promise', 'decorative', '사월십육일체 약속폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1373', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '81c7aca0-c947-4901-92c4-4d77546ca49c', '교보손글씨 2023 우선아', 'KyoboHandwriting2023UseonA', 'KyoboHandwriting2023UseonA', 'handwriting', '교보손글씨 2023 우선아폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1375', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'e50d312d-2347-407f-9328-d42356ba34bc', '기상청달콤기후체', 'KmaDalcomClimate', 'KmaDalcomClimate', 'decorative', '기상청달콤기후체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1378', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b1111f16-aeae-41d1-84b2-4327df33a9f7', '양주별산체', 'YangjuByeolsan', 'YangjuByeolsan', 'decorative', '양주별산체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1379', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '46adbe65-3600-4f59-8dcc-a7e280288a9e', '어비 채은체', 'EobiChaeun', 'EobiChaeun', 'decorative', '어비 채은체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/138', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '312e537a-dc17-4be1-86df-ede737c29747', 'HS여름물빛체2.0', 'HsSummerWaterLight20', 'HsSummerWaterLight20', 'decorative', 'HS여름물빛체2.0폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1380', NULL, 0, true, false, NOW(), NOW() );
