-- font_families 배치 2

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '4314077b-61a7-480d-ac6e-9e8c196c6261', 'KCC손기정체', 'KccSonGigeong', 'KccSonGigeong', 'decorative', 'KCC손기정체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1067', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '678f8524-7c1d-43dc-a0cb-a938e98fc75a', '코레일체', 'Korail', 'Korail', 'decorative', '코레일체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1070', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '3313f00a-834b-490e-876c-5fbe6971e718', '코레일 장체', 'KorailJang', 'KorailJang', 'decorative', '코레일 장체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1071', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '226c47e2-30c9-4070-b5a6-54aff6b7036a', '코레일 둥근고딕', 'KorailDdonggeunGothic', 'KorailDdonggeunGothic', 'gothic', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1072', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1eec3948-9b9c-456c-b070-e232386b5942', '교보손글씨 2021 성지영', 'KyoboHandwriting2021Seongjiyoung', 'KyoboHandwriting2021Seongjiyoung', 'handwriting', '교보손글씨 2021 성지영폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1075', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1f52b995-727c-4eab-a5ac-119c6e181efb', '생거진천체', 'Saenggeojincheon', 'Saenggeojincheon', 'decorative', '생거진천체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1076', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'b31dc39e-3201-4e4a-b2cc-794871da2547', '땅스부대찌개체', 'TtangsBudaeJjigae', 'TtangsBudaeJjigae', 'decorative', '이 폰트로 만든 디자인', '사용 가능', 'https://noonnu.cc/font_page/1077', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '113b1fcd-f4ae-42e9-a4cd-04a1f2abee01', '빙그레 따옴체', 'BinggreTtaom', 'BinggreTtaom', 'decorative', '빙그레 따옴체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1080', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '95053857-590d-4195-ae49-c1ebc6971002', '부크크 고딕', 'BookkGothic', 'BookkGothic', 'gothic', '부크크 고딕폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1082', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'c500da00-0e29-4303-8332-b05076a85edd', '부크크 명조', 'BookkMyungjo', 'BookkMyungjo', 'serif', '부크크 명조폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1084', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '92b49d99-dedf-4698-b2d9-afc7158bc454', '가톨릭중앙의료원체', 'CatholicCentralMedicalCenter', 'CatholicCentralMedicalCenter', 'decorative', '가톨릭중앙의료원체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1086', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '91e3dbd4-f1d1-4ace-83e0-dac9caab8793', '거친둘기마요', 'RoughDulgiMayo', 'RoughDulgiMayo', 'decorative', '거친둘기마요폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1087', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '442f5e42-0080-4b3e-afbf-12cc08ea1873', 'HS봄바람체 2.1', 'HsBombaram21', 'HsBombaram21', 'decorative', 'HS봄바람체 2.1폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1091', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '16ec33c2-4350-4a34-b7d8-ce03d627d025', 'HS집토끼체 블랙', 'HsHouseRabbitBlack', 'HsHouseRabbitBlack', 'decorative', 'HS집토끼체 블랙폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1092', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'de04c69e-c983-4081-a5c7-955d848d271a', 'HS집토끼체 라운드', 'HsJibtokiRound', 'HsJibtokiRound', 'decorative', 'HS집토끼체 라운드폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1093', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '7766f10c-e53c-4e63-bc46-32c49a0617b0', 'KCC도담도담체', 'KccDodamdodam', 'KccDodamdodam', 'decorative', 'KCC도담도담체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1094', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '1d8e6549-c6ea-4d75-a342-8cbb215de4cc', 'KCC간판체', 'KccSign', 'KccSign', 'decorative', 'KCC간판체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1095', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'a97fd42d-3c1e-48e8-b318-4c8f495d3f21', 'KCC안중근체', 'KccAnjunggeun', 'KccAnjunggeun', 'decorative', 'KCC안중근체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1096', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( 'ea88ad05-de7c-47ab-8103-4afbda54e309', 'KCC차쌤체', 'KccChaSaem', 'KccChaSaem', 'decorative', 'KCC차쌤체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1097', NULL, 0, true, false, NOW(), NOW() );

INSERT INTO font_family ( id, "nameKo", "nameEn", "fontFamily", category, provider, "licenseType", "originalUrl", description, "totalUsageCount", "isActive", "isFeatured", "createdAt", "updatedAt" ) VALUES ( '9a458b02-0919-49f3-abea-ae4a2ded374f', 'KCC무럭무럭체', 'KccMurukMuruk', 'KccMurukMuruk', 'decorative', 'KCC무럭무럭체폰트로 만든 디자인 올리기', '사용 가능', 'https://noonnu.cc/font_page/1098', NULL, 0, true, false, NOW(), NOW() );
